### ISSUE TITLE
bug反馈：执行清空其他文件

### ISSUE THREAD

**Issue by salmon3g** [dianbanjiu/dianbanjiu.github.io#1]
生成文件丢失，大部分内容都被清除了。请大佬帮忙看看

仓库地址：https://github.com/salmon3g/salmon3g.github.io/tree/main

**Comment by dianbanjiu** [comment]
看了一下，你的主题目录 themes/PaperMod 在远程仓库里面是空的，所以编译出的内容才是空的，你可以  
1. 直接把主题的文件复制到你的 themes/PaperMod 下面  
2. 把主题设置为 submodule，在 action 的时候把主题也拉下来
3. 在 action 的时候使用 git 直接把主题拉取到 themes 下面

你可以随便选择一种方式，因为我对主题会有一些自定义的部分，所以我现在用的是第一种方式
